//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MascotasEFApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTA
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string RAZA { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string NOMBREDUENO { get; set; }
    }
}
